export const customers = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '1234567890',
    address: '123 Main Street',
    level: 'silver',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '9876543210',
    address: '456 Elm Avenue',
    level: 'gold',
  },
  {
    id: '3',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    phone: '5551234567',
    address: '789 Oak Lane',
    level: 'bronze',
  },
  {
    id: '4',
    name: 'Bob Anderson',
    email: 'bob.anderson@example.com',
    phone: '7778889999',
    address: '321 Pine Road',
    level: 'gold',
  },
  {
    id: '5',
    name: 'Emily Wilson',
    email: 'emily.wilson@example.com',
    phone: '1112223333',
    address: '555 Cedar Street',
    level: 'silver',
  },
  {
    id: '6',
    name: 'Michael Thompson',
    email: 'michael.thompson@example.com',
    phone: '4445556666',
    address: '222 Maple Avenue',
    level: 'bronze',
  },
  {
    id: '7',
    name: 'Sophia Brown',
    email: 'sophia.brown@example.com',
    phone: '7774441111',
    address: '777 Oak Lane',
    level: 'silver',
  },
  {
    id: '8',
    name: 'Oliver Martinez',
    email: 'oliver.martinez@example.com',
    phone: '8885552222',
    address: '666 Pine Road',
    level: 'gold',
  },
  {
    id: '9',
    name: 'Emma Davis',
    email: 'emma.davis@example.com',
    phone: '9996663333',
    address: '999 Cedar Street',
    level: 'bronze',
  },
  {
    id: '10',
    name: 'James Wilson',
    email: 'james.wilson@example.com',
    phone: '3336669999',
    address: '111 Maple Avenue',
    level: 'gold',
  },
  {
    id: '11',
    name: 'Ava Harris',
    email: 'ava.harris@example.com',
    phone: '7779993333',
    address: '555 Elm Avenue',
    level: 'silver',
  },
  {
    id: '12',
    name: 'Noah Taylor',
    email: 'noah.taylor@example.com',
    phone: '8883336666',
    address: '222 Pine Road',
    level: 'bronze',
  },
  {
    id: '13',
    name: 'Isabella Clark',
    email: 'isabella.clark@example.com',
    phone: '5551117777',
    address: '888 Oak Lane',
    level: 'silver',
  },
  {
    id: '14',
    name: 'Liam Lewis',
    email: 'liam.lewis@example.com',
    phone: '9998887777',
    address: '444 Cedar Street',
    level: 'gold',
  },
  {
    id: '15',
    name: 'Mia Turner',
    email: 'mia.turner@example.com',
    phone: '6662224444',
    address: '777 Maple Avenue',
    level: 'bronze',
  },
];
