import { Orders } from '../models/order';

// I want to change productName with Red Tulip Bouquet, Blue Tulip Bouquet, Yellow Tulip Bouquet, Pink Tulip Bouquet, White Tulip Bouquet, Red and White Tulip Bouquet, Mixed Color Tulip Bouquet, Purple Tulip Bouquet, Orange Tulip Bouquet, Black Tulip Bouquet

export const orders: Orders[] = [
  {
    orderId: '1',
    productName: 'Red Tulip Bouquet',
    customerName: 'John Doe',
    orderDate: new Date('2022-10-01'),
    quantity: 5,
    orderStatus: 'Delivered',
  },
  {
    orderId: '2',
    productName: 'Blue Tulip Bouquet',
    customerName: 'Jane Doe',
    orderDate: new Date('2022-10-02'),
    quantity: 3,
    orderStatus: 'Shipped',
  },
  {
    orderId: '3',
    productName: 'Red and White Tulip Bouquet',
    customerName: 'Emily Clark',
    orderDate: new Date('2022-10-03'),
    quantity: 7,
    orderStatus: 'Processing',
  },
  {
    orderId: '4',
    productName: 'White Tulip Bouquet',
    customerName: 'Michael Smith',
    orderDate: new Date('2022-10-04'),
    quantity: 2,
    orderStatus: 'Cancelled',
  },
  {
    orderId: '5',
    productName: 'Yellow Tulip Bouquet',
    customerName: 'Sarah Johnson',
    orderDate: new Date('2022-10-05'),
    quantity: 4,
    orderStatus: 'Delivered',
  },
  {
    orderId: '6',
    productName: 'Yellow Tulip Bouquet',
    customerName: 'James Williams',
    orderDate: new Date('2022-10-06'),
    quantity: 6,
    orderStatus: 'Delivered',
  },
  {
    orderId: '7',
    productName: 'Pink Tulip Bouquet',
    customerName: 'Patricia Brown',
    orderDate: new Date('2022-10-07'),
    quantity: 1,
    orderStatus: 'Processing',
  },
  {
    orderId: '8',
    productName: 'White Tulip Bouquet',
    customerName: 'Robert Davis',
    orderDate: new Date('2022-10-08'),
    quantity: 2,
    orderStatus: 'Cancelled',
  },
  {
    orderId: '9',
    productName: 'Red and White Tulip Bouquet',
    customerName: 'Jennifer Miller',
    orderDate: new Date('2022-10-09'),
    quantity: 8,
    orderStatus: 'Shipped',
  },
  {
    orderId: '10',
    productName: 'Mixed Color Tulip Bouquet',
    customerName: 'William Wilson',
    orderDate: new Date('2022-10-10'),
    quantity: 5,
    orderStatus: 'Delivered',
  },
  {
    orderId: '11',
    productName: 'Purple Tulip Bouquet',
    customerName: 'Linda Moore',
    orderDate: new Date('2022-10-11'),
    quantity: 3,
    orderStatus: 'Processing',
  },
  {
    orderId: '12',
    productName: 'Orange Tulip Bouquet',
    customerName: 'David Taylor',
    orderDate: new Date('2022-10-12'),
    quantity: 2,
    orderStatus: 'Shipped',
  },
  {
    orderId: '13',
    productName: 'Black Tulip Bouquet',
    customerName: 'Karen Anderson',
    orderDate: new Date('2022-10-13'),
    quantity: 1,
    orderStatus: 'Delivered',
  },
];
