import { Product } from '../models/product';

export const products: Product[] = [
  {
    productName: 'Red Tulip Bouquet',
    productCategory: 'Flowers',
    date: '2023-05-01',
    color: 'red',
    price: 12.99,
    amount: 50,
    vendor: 'Floral Delights',
    isStockAvailable: true,
    demandRating: 8,
  },

  {
    productName: 'Blue Tulip Bouquet',
    productCategory: 'Flowers',
    date: '2023-04-25',
    color: 'blue',
    price: 14.99,
    amount: 30,
    vendor: 'Blossom Gardens',
    isStockAvailable: true,
    demandRating: 7,
  },

  {
    productName: 'Yellow Tulip Bouquet',
    productCategory: 'Flowers',
    date: '2023-04-30',
    color: 'yellow',
    price: 11.99,
    amount: 40,
    vendor: 'Sunshine Florals',
    isStockAvailable: true,
    demandRating: 6,
  },

  {
    productName: 'Pink Tulip Bouquet',
    productCategory: 'Flowers',
    date: '2023-05-02',
    color: 'pink',
    price: 16.99,
    amount: 20,
    vendor: 'Rose Petal Florist',
    isStockAvailable: true,
    demandRating: 9,
  },

  {
    productName: 'White Tulip Bouquet',
    productCategory: 'Flowers',
    date: '2023-04-28',
    color: 'white',
    price: 10.99,
    amount: 60,
    vendor: 'Pure Elegance Flowers',
    isStockAvailable: true,
    demandRating: 7,
  },

  {
    productName: 'Red and White Tulip Bouquet',
    productCategory: 'Flowers',
    date: '2023-05-03',
    color: 'red',
    price: 14.99,
    amount: 30,
    vendor: 'Petals & Blooms',
    isStockAvailable: true,
    demandRating: 7,
  },

  {
    productName: 'Mixed Color Tulip Bouquet',
    productCategory: 'Flowers',
    date: '2023-05-05',
    color: 'red',
    price: 18.99,
    amount: 15,
    vendor: 'Rainbow Florals',
    isStockAvailable: true,
    demandRating: 8,
  },
  {
    productName: 'Purple Tulip Bouquet',
    productCategory: 'Flowers',
    date: '2023-05-10',
    color: 'pink',
    price: 13.99,
    amount: 25,
    vendor: 'Violet Gardens',
    isStockAvailable: true,
    demandRating: 7,
  },
  {
    productName: 'Orange Tulip Bouquet',
    productCategory: 'Flowers',
    date: '2023-05-08',
    color: 'pink',
    price: 12.99,
    amount: 35,
    vendor: 'Citrus Blossoms',
    isStockAvailable: true,
    demandRating: 6,
  },

  {
    productName: 'Black Tulip Bouquet',
    productCategory: 'Flowers',
    date: '2023-05-12',
    color: 'blue',
    price: 24.99,
    amount: 10,
    vendor: 'Midnight Blooms',
    isStockAvailable: true,
    demandRating: 9,
  },
];
